// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrexcoubiqzdiegfxsjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpyZXhjb3ViaXF6ZGllZ2Z4c2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTEyNzgsImV4cCI6MjA3MzA2NzI3OH0.LNATlYRlYnEjv2hOuzlw4bgXBF_tpBI5fhXjlxeSxgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});